import json
from pathlib import Path
import tempfile
import unittest

from scripts.silent_payment_test_receiver import (
    RECEIVER_FORMAT,
    _parse_transaction,
    generate_receiver,
    load_receiver,
    recover_transaction,
    scan_transaction,
)


ROOT = Path(__file__).resolve().parents[1]
SCAN_SECRET = 11
SPEND_SECRET = 29
ADDRESS = (
    "tsp1qqdm54elctz55z8j77sjxkuxxt2k9vjvcp0juz7y3h0kp0z2a5qyvkqky"
    "f5fvwpjasyhg4neg6l9mr8usz8kdn60a72qmpe4rkh586gh8mv96helr"
)
MAINNET_ADDRESS = (
    "sp1qqdm54elctz55z8j77sjxkuxxt2k9vjvcp0juz7y3h0kp0z2a5qyvkqky"
    "f5fvwpjasyhg4neg6l9mr8usz8kdn60a72qmpe4rkh586gh8mv34hv4c"
)


class TestReceiverUtility(unittest.TestCase):
    def test_generate_creates_testnet_receiver(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "receiver.json"
            receiver = generate_receiver(path)
            self.assertTrue(path.is_file())
            self.assertEqual("testnet", receiver["network"])
            self.assertTrue(receiver["silent_payment_address"].startswith("tsp1"))
            self.assertEqual(64, len(receiver["scan_secret"]))
            self.assertEqual(64, len(receiver["spend_secret"]))

    def test_generate_creates_mainnet_receiver(self):
        with tempfile.TemporaryDirectory() as directory:
            receiver = generate_receiver(
                Path(directory) / "receiver.json",
                network="mainnet",
            )
            self.assertEqual("mainnet", receiver["network"])
            self.assertTrue(receiver["silent_payment_address"].startswith("sp1"))

    def test_legacy_build_receiver_file_remains_compatible(self):
        with tempfile.TemporaryDirectory() as directory:
            receiver_path = Path(directory) / "old-build-receiver.json"
            receiver_path.write_text(
                json.dumps({
                    "format": RECEIVER_FORMAT,
                    "network": "mainnet",
                    "silent_payment_address": MAINNET_ADDRESS,
                    "scan_secret": f"{SCAN_SECRET:064x}",
                    "spend_secret": f"{SPEND_SECRET:064x}",
                    "warning": "Generated by the earlier unpublished build.",
                }),
                encoding="utf-8",
            )
            scan_secret, spend_secret, address, network = load_receiver(
                receiver_path
            )
            self.assertEqual(SCAN_SECRET, scan_secret)
            self.assertEqual(SPEND_SECRET, spend_secret)
            self.assertEqual(MAINNET_ADDRESS, address)
            self.assertEqual("mainnet", network)

    def test_scans_legacy_and_segwit_signed_transactions(self):
        results = json.loads(
            (
                ROOT
                / "test-results/electrum-4.8.0-testnet-cli-integration.json"
            ).read_text(encoding="utf-8")
        )
        with tempfile.TemporaryDirectory() as directory:
            receiver_path = Path(directory) / "receiver.json"
            receiver_path.write_text(
                json.dumps({
                    "format": RECEIVER_FORMAT,
                    "network": "testnet",
                    "silent_payment_address": ADDRESS,
                    "scan_secret": f"{SCAN_SECRET:064x}",
                    "spend_secret": f"{SPEND_SECRET:064x}",
                }),
                encoding="utf-8",
            )
            for case in results["cases"]:
                with self.subTest(input_type=case["input_type"]):
                    scanned = scan_transaction(
                        receiver_path,
                        case["raw_transaction"],
                    )
                    self.assertEqual("match", scanned["status"])
                    self.assertEqual(case["signed_txid"], scanned["txid"])
                    self.assertEqual(1, len(scanned["matches"]))
                    match = scanned["matches"][0]
                    self.assertEqual(case["amount_sat"], match["amount_sat"])
                    self.assertEqual(
                        case["recipient_scriptpubkey"],
                        match["scriptpubkey"],
                    )

    def test_builds_signed_mainnet_recovery_transaction(self):
        results = json.loads(
            (
                ROOT
                / "test-results/electrum-4.8.0-mainnet-cli-integration.json"
            ).read_text(encoding="utf-8")
        )
        receiving_case = results["cases"][2]
        witness_program = bytes.fromhex("22" * 20)
        from electrum import segwit_addr

        destination = segwit_addr.bech32_encode(
            segwit_addr.Encoding.BECH32,
            "bc",
            [0] + list(segwit_addr.convertbits(witness_program, 8, 5)),
        )
        with tempfile.TemporaryDirectory() as directory:
            receiver_path = Path(directory) / "receiver.json"
            receiver_path.write_text(
                json.dumps({
                    "format": RECEIVER_FORMAT,
                    "network": "mainnet",
                    "silent_payment_address": MAINNET_ADDRESS,
                    "scan_secret": f"{SCAN_SECRET:064x}",
                    "spend_secret": f"{SPEND_SECRET:064x}",
                }),
                encoding="utf-8",
            )
            recovery = recover_transaction(
                receiver_path,
                receiving_case["raw_transaction"],
                destination=destination,
                fee_sat=500,
            )
            self.assertEqual("signed", recovery["status"])
            self.assertEqual(500, recovery["fee_sat"])
            self.assertEqual(
                receiving_case["amount_sat"] - 500,
                recovery["output_amount_sat"],
            )
            parsed = _parse_transaction(recovery["raw_transaction"])
            self.assertEqual(recovery["txid"], parsed.txid)
            self.assertEqual(1, len(parsed.inputs))
            self.assertEqual(1, len(parsed.inputs[0].witness))
            self.assertEqual(64, len(parsed.inputs[0].witness[0]))
            self.assertEqual(
                receiving_case["amount_sat"] - 500,
                parsed.outputs[0].value,
            )


if __name__ == "__main__":
    unittest.main()
